name: TEST Make swagger artifacts

#on:
#  push:
#    branches:
#    - main
  # pull_request:
  #   branches:
  #     - main
  #   types: [opened, synchronize]
  #   tags:
  #     - v*
on: workflow_dispatch

jobs:
  build-image-and-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build, tag, and push image to Amazon ECR
        id: ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dreamkast-api-mock
          GITHUB_REF: ${{ github.ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          echo REF "$GITHUB_REF"
          echo HEAD REF "$GITHUB_HEAD_REF"
          echo SHA "$GITHUB_SHA"
          IMAGE_TAG=$(echo "$GITHUB_REF" | sed -e 's,.*/\(.*\),\1,')
          [[ "$GITHUB_REF" == "refs/tags/"* ]] && IMAGE_TAG=$(echo "$IMAGE_TAG" | sed -e 's/^v//')

          IMAGE_WITH_TAG="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
          IMAGE_WITH_SHA="${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_SHA}"

          echo "::set-output name=IMAGE_WITH_TAG::${IMAGE_WITH_TAG}"
          echo "::set-output name=IMAGE_WITH_SHA::${IMAGE_WITH_SHA}"

      - name: Checkout dreamkast-infra
        uses: actions/checkout@v3
        with:
          repository: hrk091/dreamkast-infra
          path: dreamkast-infra
          token:  ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        run: |
          cd dreamkast-infra/manifests/app/dreamkast-api-mock/base
          kustomize edit set image ${{ steps.ecr.outputs.IMAGE_WITH_SHA }}
          cat kustomization.yaml

      - name: Commit files
        run: |
          cd dreamkast-infra/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -am "Bump docker tag"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: hrk091/dreamkast-infra
          directory: dreamkast-infra
          branch: main

      - name: Checkout dreamkast-ui
        uses: actions/checkout@v3
        with:
          repository: hrk091/dreamkast-ui
          path: dreamkast-ui
          token:  ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Copy swagger.yml
        run: |
          cp -f ./schemas/swagger.yml ./dreamkast-ui/schemas/swagger.yml

      - name: Generate RTKQuery Client
        run: |
          mkdir -p tmp
          cd tmp
          echo $PWD
          echo ${{ github.workspace }}
          yarn add ts-node @rtk-query/codegen-openapi
          npx @rtk-query/codegen-openapi ${{ github.workspace }}/dreamkast-ui/rtk-query-codegen-openapi.config.ts

      - name: Generate OpenApi Client
        uses: docker://openapitools/openapi-generator-cli:v5.3.1
        with:
          # TODO remove --skip-validate-spec flag
          args: generate -g typescript-axios --reserved-words-mappings abstract=abstract -i ./schemas/swagger.yml -o ./dreamkast-ui/src/client-axios --skip-validate-spec

      - name: Commit files
        working-directory: dreamkast-ui/
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -am "Update src/client-axios (generated by openapi-generator)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: hrk091/dreamkast-ui
          directory: dreamkast-ui
          branch: openapi-generator/client-axios

      - name: Create Pull Request
        uses: "actions/github-script@v6"
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const pr = await github.rest.pulls.create({
              owner: "hrk091",
              repo: "dreamkast-ui",
              title: "Automated PR (dreamkast swagger.yml update)",
              body: "**This PR is automatically created**",
              head: "openapi-generator/client-axios",
              base: "main"
            });
